all: compile link

compile:
	g++ -c main.cpp -I"D:\Studia\Projekt c++\SFML\SFML-2.6.1\include"

link:
	g++ main.o -o game -L"D:\Studia\Projekt c++\SFML\SFML-2.6.1\lib" -lsfml-graphics -lsfml-window -lsfml-system
